Feature/profile page
AlekseiKolesnikov/clothing-store-webapp pull request #10
Opened 2023-10-15 21:15 UTC by AlekseiKolesnikov

Исправил баг с не появлением обратно изначальной строки с ФИО и Телефоном если ничего не было введено

2023-10-16 20:03 UTC, ShadowZilot commented on src/app/shared/telegram_ui/telegram-back-button.ts
> +          Telegram.WebApp.BackButton.onClick(() => {
А почему не поправил back click

2023-10-17 13:17 UTC, AlekseiKolesnikov commented on src/app/shared/telegram_ui/telegram-back-button.ts
> +          Telegram.WebApp.BackButton.onClick(() => {
Посмотри последний commit

2023-10-17 19:28 UTC, ShadowZilot requested changes

2023-10-17 19:28 UTC, ShadowZilot commented on src/app/features/feature-profile/components/profile-satus/profile-status.component.ts
> +
Выноси вот такие вот строки в константы

2023-10-17 19:28 UTC, ShadowZilot commented on src/app/features/feature-profile/components/profile-delivery-inf/profile-delivery-inf.component.ts
> +      this.inputResultStateService.setNameInputResultState(true)
В константы

2023-10-17 19:28 UTC, ShadowZilot commented on src/app/app.module.ts
> +    ServiceWorkerModule.register('ngsw-worker.js', {
Что это такое?

2023-10-19 14:16 UTC, AlekseiKolesnikov commented on src/app/app.module.ts
> +    ServiceWorkerModule.register('ngsw-worker.js', {
Убрал, это я пытался сделать ServiceWorker думая что он для другого преднозначен

2023-10-23 20:11 UTC, merged