Input data local storage bind
AlekseiKolesnikov/clothing-store-webapp pull request #23
Opened 2023-12-29 01:53 UTC by AlekseiKolesnikov

2023-12-30 21:35 UTC, ShadowZilot requested changes

2023-12-30 21:35 UTC, ShadowZilot commented on src/app/features/feature-delivery/components/personal-data-field/personal-data-field.component.ts
> +    }
А нельзя ли сделать так чтобы deliveryDataService сам клал данные в localStorageService ?

2023-12-30 21:35 UTC, ShadowZilot commented on src/app/features/feature-delivery/pages/distribution-address-page/distribution-address-page.component.ts
> +    })
Отныне и впредь за каждую подписку в воздухе да ещё в конструкторе, я буду ставить тебе клоуна 🤡

2023-12-30 21:35 UTC, ShadowZilot commented on src/app/features/feature-delivery/pages/distribution-points-page/distribution-points-page.component.ts
> +        this.citiesArray = data
🤡

2023-12-30 21:35 UTC, ShadowZilot commented on src/app/features/feature-delivery/services/data-local-store.service.ts
> +  protected addressKey: string = this.localStorageKeysService.DELIVERY_ADDRESS_KEY
Ну зачем так делать? Почему нельзя сразу константы использовать зачем для них поля делать??

2023-12-30 21:35 UTC, ShadowZilot commented on src/app/features/feature-delivery/services/local-storage-data-check.service.ts
> +  }
Посмотрел на то как ты используешь этот метод, и вот что я предлагаю делать, передавать в параметры не просто data, а default value, чтобы потом не проверять на пустоту дополнительно

2023-12-30 21:35 UTC, ShadowZilot commented on src/app/local-storage.service.ts
>    }
Метод JSON.stringify может выкинуть TypeError было бы здорово обрабатывать это здесь.

2024-01-04 00:34 UTC, AlekseiKolesnikov commented on src/app/features/feature-delivery/components/personal-data-field/personal-data-field.component.ts
> +    }
Переделал в 24 реквесте

2024-01-04 00:35 UTC, AlekseiKolesnikov commented on src/app/features/feature-delivery/pages/distribution-points-page/distribution-points-page.component.ts
> +        this.citiesArray = data
Переделал в 20 реквесте

2024-01-04 00:52 UTC, AlekseiKolesnikov commented on src/app/features/feature-delivery/services/data-local-store.service.ts
> +  protected addressKey: string = this.localStorageKeysService.DELIVERY_ADDRESS_KEY
переделал

2024-01-04 20:09 UTC, ShadowZilot approved these changes

2024-01-05 00:17 UTC, merged